### ISSUE TITLE
Inconsistend depth after move

### ISSUE THREAD

**Issue by qyloxe** [mesqueeb/quasar-app-extension-draggable#2]
When you move "Introject" before "Nova", "Nova" keeps depth==2. Or "Introject" keeps depth==0. Can't decide which one is incorrect. Probably, the "Introject" should have the same level as "Increasedly"==1. Maybe similar behaviour as in:
https://vuejsexamples.com/a-drag-drop-hierarchical-list-made-as-a-vue-component/
or:
https://vuejsexamples.com/a-vue-js-draggable-tree-component/

![image](https://user-images.githubusercontent.com/467508/57527988-5baa7400-7331-11e9-9112-a729e209ddc1.png)

**Comment by mesqueeb** [comment]
Hi @qyloxe thanks for this issue.

I was thinking of solving this for a while now.

I never saw "vue-nestable" it seems like a really good component!! XD
If I'd had found it before I might have never made my extension lol.

But anyway, since I'm already this far, I will persevere!!

This is the new behaviour I plan to implement:
<img width="794" alt="Screenshot 2019-05-11 07 44 35" src="https://user-images.githubusercontent.com/3253920/57560550-ff436500-73c1-11e9-872d-67a8ece2fc27.png">

**Comment by mesqueeb** [comment]
@qyloxe Look at it in action:

![2019-05-11 08 10 22](https://user-images.githubusercontent.com/3253920/57560991-4fbbc200-73c4-11e9-9db1-389c0ae63e49.gif)

just working out the details now!

**Comment by qyloxe** [comment]
Sweet, And would it be possible to put an Introject under Elaborating at depth==1 with mouse/touch only?
Your code is very elegant.

**Comment by mesqueeb** [comment]
Hi!
The update is now pushed and live!
You can play around with it in the [DEMO](https://quasar-app-extension-draggable.netlify.com). 🔞

For indenting / unindenting a row without keyboard I'll open a new issue!

<sub>--<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>
